apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
spec:
  project: default
  source:
    repoURL: 'https://github.com/yourusername/cosmetics-ecommerce-devops.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true